{% set name = "based58" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/kevinheavey/based58/archive/refs/tags/{{ version }}.tar.gz
  sha256: 5c0c5062151b96e48f0d7248a8b3c59f478676d47f922dba17676d496da01e1a

build:
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - maturin >=0.14.12
    - pip
    - poetry
    - python
  run:
    - python
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]

test:
  imports:
    - based58
  requires:
    - pip
    - pytest
  source_files:
    - tests
  commands:
    - pip check
    - pytest

about:
  home: https://github.com/kevinheavey/based58
  summary: 'A fast base-58 Python library'
  description: |
    based58 is a fast Python library for Base58 encoding and decoding.
    It includes support for Base58Check and configurable alphabets.
    It is significantly faster than the pure-Python base58 library, as it calls the Rust bs58 library under the hood.
    The API mimics that of the base58 library, with the exception that string inputs are not supported, only bytes.
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  doc_url: https://kevinheavey.github.io/based58/

extra:
  recipe-maintainers:
    - MementoRC
